### ISSUE TITLE
Ensure Player Sprite Is Unique In Victory HUD

### ISSUE THREAD

**Issue by J-Dan23** [Lightcaster-Studios/Beamerman#140]
Victory HUD shows repeated player sprite sometimes.
![image](https://user-images.githubusercontent.com/55853397/114154489-0b8c2000-9953-11eb-9167-af0dba286277.png)

**Comment by iskandarzulkarnaien** [comment]
Chances are something is causing repeated addition into the data structure that stores the dead players.

**Comment by iskandarzulkarnaien** [comment]
Fixed by #144
