### ISSUE TITLE
[BUG] When player is running, laser might go behind player 

### ISSUE THREAD

**Issue by raniceyue** [Lightcaster-Studios/Beamerman#33]
I am not sure how to describe this issue but basically when the player is running and shoots a laser, sometimes the laser gets spawned a little bit behind the player, and this leads to the laser passing through the player. 

[GIF of bug](https://imgur.com/a/4lrpZDD)

**Comment by iskandarzulkarnaien** [comment]
I chock this up to the player being too fast or the lazer being too slow. Ill experiment with this and fix it in PR #31

**Comment by iskandarzulkarnaien** [comment]
iirc, this problem was because the projectile was actually spawning <strong> behind </strong> the player. Fixed in #31
