### ISSUE TITLE
End Game UI

### ISSUE THREAD

**Issue by raniceyue** [Lightcaster-Studios/Beamerman#40]
I am not sure how we should do this, basically we need some kind of UI or cutscene when the last player is still standing. 

- For multiplayer, immediately after one player dies, the game ends?
- For single player, the game ends only once all AIs are killed? 

Right now, for the sake of the playtest, I was thinking the first option is better

**Comment by raniceyue** [comment]
End game UI for DEFEAT done in #94

**Comment by iskandarzulkarnaien** [comment]
Fixed by #133
