### ISSUE TITLE
Playtest 1 Bug Report 1

### ISSUE THREAD

**Issue by Justin-Ong** [Lightcaster-Studios/Beamerman#73]
1. The laser seems to clip through mirrors slightly before reflection is applied, which can cause the laser to be destroyed instead of reflecting when there is a wall past the mirror and the player stands close to the mirror. Please see [this video](https://drive.google.com/file/d/10WDBzvXgvOO7Uw-2Ii4Mq-Mw_vQlDBBi/view?usp=sharing).

2. The mirror at the top-middle of the arena has incorrect reflection. Instead of reflecting back towards the player as with all other mirrors perpendicular to the cardinal directions, it reflects to the left. Please see [this video](https://drive.google.com/file/d/1i0IInG0ECP6tbQHcIgcjDEagJaIz18Ml/view?usp=sharing).

3. The laser seems to spawn slightly behind the player. This causes issues such as splitters triggering when the player is not facing them, or crates being destroyed when the player's back is to them. In addition, it causes issues with the splitters when facing left, where the forward laser does not even appear. Please see [this video](https://drive.google.com/file/d/1hjHGzyRGgxEesj-LbWWiD4GxTiyJZR4U/view?usp=sharing).

4. By standing in the right spot next to a diagonal mirror, the player can fire a laser such that it damages themselves. Please see [this video](https://drive.google.com/file/d/1x_IH6CPnu-ecGsm4AtJODu3Jl2n2xpIq/view?usp=sharing).

**Comment by iskandarzulkarnaien** [comment]
Hi @Justin-Ong, thanks for playing our game and for the very thorough and insightful feedback.

I'll raise the necessary issues with regards to your report so the team can get started on bug fixes. 

We really appreciate your input, especially for the accompanying videos since it makes it crystal clear what and where the issues are! :)

**Comment by iskandarzulkarnaien** [comment]
@Lightcaster-Studios/beamerman-devs do take note of these issues. I'll be closing this issue in a day or so to avoid spamming Justin.
