### ISSUE TITLE
UI Scaling Issue

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [Lightcaster-Studios/Beamerman#77]
The UI does not scale automatically and looks weird/blocks the arena on certain screens/resolutions.

Here is an image from one of our playtesters:
![image](https://user-images.githubusercontent.com/43085796/112766378-2225a380-9044-11eb-9863-0964f3e809f6.png)

**Comment by raniceyue** [comment]
Ok on it

**Comment by raniceyue** [comment]
Resolved in #94

**Comment by iskandarzulkarnaien** [comment]
Actually, I don't think this is fixed. We might need to force a fixed resolution or make the UI elements scale/reposition them with screen size.

**Comment by iskandarzulkarnaien** [comment]
Fixed in #133
