### ISSUE TITLE
Should Player Have Multiple Temp Power Ups At Once

### ISSUE THREAD

**Issue by J-Dan23** [Lightcaster-Studios/Beamerman#80]
Eg. A player already has an active Glass Armor. Should stepping on Temp Armor:
1. Override Glass Armor
2. Run concurrently with Glass Armor
3. Not be picked up at all (aka stays on ground)

**Comment by iskandarzulkarnaien** [comment]
I'm impartial towards both 1&2. I'm not really in favor of 3 since I feel that players should be incentivised and rewarded for picking up powerups, even if the reward is denying it from your enemy

**Comment by J-Dan23** [comment]
Temp Power Ups are overriden upon picking up a new temp power up.
