### ISSUE TITLE
AI walks off the map in mayhem mode

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [Lightcaster-Studios/Beamerman#90]
When tiles fall off in mayhem mode, the AI doesn't seem to recognize this and will willingly walk off

**Comment by raniceyue** [comment]
> 
> 
> suggestions:
> shrink nav mesh during mayhem mode. I'm not sure when/ how would mayhem mode work, but I believe nav mesh shrinkage can operate alongside this.
> 
> use nav link on all tiles?

I think you need to read our GDD again, details of how mayhem mode works are in the GDD

**Comment by J-Dan23** [comment]
There's a "dynamic runtime generation" for the navmesh, that in theory _should_ handle situations like these. I'll test it out.
